### ISSUE TITLE
Clock Frequency

### ISSUE THREAD

**Issue by rjs5327** [arduino-libraries/Arduino_MKRMEM#6]
I been reading through this code and the clock frequency is set to 104MHz statically.  But the Spec Sheet calls for the 104MHz 3-3.6V  except for Cmd 03h (Read Data)  which is to be 50Mhz.  Has there been any issues maintaining the clock speed that high when the spec sheet calls for a derate on the read commands?
Pg66
https://www.winbond.com/resource-files/w25q16dv_revi_nov1714_web.pdf

**Comment by rjs5327** [comment]
I found the answer the MKR clock is at 48Mhz so the max speed is 48.  The library should really be fixed to take this into account incase faster chip is released in the MKR series.

**Comment by aentinger** [comment]
Hi @rjs5327 :wave: Thank you very much for catching this. I've choosen to leave the SPI settings to 104 MHz because a faster MCU might use a faster data transaction rate then, however - in case of `Read Data` this might be a problem. Would you mind to prepare a pull request with a separate (and lower) SPI settings configuration for `Read Data` ?
